KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_producer-user="ProducerPass123"
    user_consumer-user="ConsumerPass123"
    user_no-access-user="NoAccessPass123";
};

KafkaController {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret";
};
